FROM lamp-prod
RUN export DEBIAN_FRONTEND=noninteractive && \
  apt update && apt -y upgrade && \
  apt install -y build-essential python wget
RUN wget https://deb.nodesource.com/setup_6.x && chmod +x setup_6.x && ./setup_6.x && apt install -y nodejs
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/www/html/*
RUN mkdir /var/www/c9 && cd /var/www/c9 && \
  git clone git://github.com/c9/core.git . && \
  scripts/install-sdk.sh
CMD nodejs /var/www/c9/server.js -w /var/www/html/
